package MyApp;

import MyLibs.Date;
import MyLibs.LoginDetails;
import MyLibs.Manager;
import java.awt.event.KeyEvent;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class CarRecordsPasswordForm extends javax.swing.JFrame {

    CarRecordsForm main_form;
    ImageIcon info_icon = new ImageIcon("src/img/info_small.png");
    ImageIcon error_icon = new ImageIcon("src/img/error_small.png");

    /**
     * define all hard coded managers here
     */
    Manager test = new Manager("Senac",
            1,
            new LoginDetails("senac", "admin"),
            new Date(1, 1, 1970));
    Manager test2 = new Manager("Adriana",
            2,
            new LoginDetails("adriana", "admin"),
            new Date(1, 1, 1970));
    Manager test3 = new Manager("ParkPulse",
            3,
            new LoginDetails("parkpulse", "admin"),
            new Date(1, 1, 1970));

    /**
     * Creates new form CarRecordsPasswordForm
     */
    public CarRecordsPasswordForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        loginHeader = new javax.swing.JLabel();
        managerUsername = new javax.swing.JTextField();
        managerPassword = new javax.swing.JPasswordField();
        managerUsernameLabel = new javax.swing.JLabel();
        managerPasswordLabel = new javax.swing.JLabel();
        managerLoginButton = new javax.swing.JButton();
        programQuitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginHeader.setBackground(new java.awt.Color(255, 255, 255));
        loginHeader.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        loginHeader.setText("Faça login no ParkPulse (SGE)");
        getContentPane().add(loginHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 240, 30));

        managerUsername.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        getContentPane().add(managerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 210, -1));

        managerPassword.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerPasswordActionPerformed(evt);
            }
        });
        managerPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                managerPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(managerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 210, -1));

        managerUsernameLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerUsernameLabel.setText("Usuário:");
        getContentPane().add(managerUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        managerPasswordLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerPasswordLabel.setText("Senha:");
        getContentPane().add(managerPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        managerLoginButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerLoginButton.setText("Login");
        managerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(managerLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        programQuitButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        programQuitButton.setText("Sair");
        programQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programQuitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programQuitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 160, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parkpulse (1).png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 300));
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 330, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estacionamentoiesp.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 690, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLoginButtonActionPerformed
        loginLogic();
    }//GEN-LAST:event_managerLoginButtonActionPerformed

    private void programQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programQuitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_programQuitButtonActionPerformed

    private void managerPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_managerPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                loginLogic();
            } catch (Exception e) {
                displayLoginError();
            }
        }
    }//GEN-LAST:event_managerPasswordKeyPressed

    private void managerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerPasswordActionPerformed

    private void managerLogin(Manager m, String u, String p) {
        if (m.loginAttempt(u, p)) {
            JOptionPane.showMessageDialog(this,
                    "Bem vindo, " + m.getName(),
                    "Login realizado com sucesso",
                    JOptionPane.INFORMATION_MESSAGE,
                    info_icon);

            main_form = new CarRecordsForm();
            main_form.setLoggedInManager(m);
            main_form.replaceUserLabel();

            this.setVisible(false);
            main_form.setVisible(true);
        } // Login passed
        else {
            displayLoginError();
        } // Login failed
    }

    private void displayLoginError() {
        JOptionPane.showMessageDialog(this,
                "Error logging in.\nMake sure you have entered a correct username/password combo.",
                "Error",
                JOptionPane.ERROR_MESSAGE,
                error_icon);
    }

    private void loginLogic() {
        String enteredUser = managerUsername.getText();
        char[] enteredPass = managerPassword.getPassword();
        String passAsString = new String(enteredPass);

        switch (enteredUser) {
            case "senac":
                managerLogin(test, enteredUser, passAsString);
                break;
            case "adriana":
                managerLogin(test2, enteredUser, passAsString);
                break;
            case "parkpulse":
                managerLogin(test3, enteredUser, passAsString);
                break;
            default:
                displayLoginError();
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("OptionPane.messageFont", new Font("Verdana", Font.PLAIN, 12));
        UIManager.put("OptionPane.buttonFont", new Font("Verdana", Font.PLAIN, 11));
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRecordsPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRecordsPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JButton managerLoginButton;
    private javax.swing.JPasswordField managerPassword;
    private javax.swing.JLabel managerPasswordLabel;
    private javax.swing.JTextField managerUsername;
    private javax.swing.JLabel managerUsernameLabel;
    private javax.swing.JButton programQuitButton;
    // End of variables declaration//GEN-END:variables
}
